
### User Registration
POST  http://localhost:5000/api/users
Content-Type: application/json

{
"username" : "USER1",
"email" : "usreml1@gmail.com" ,
"password" : "USERP"

}


### Login
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
"username" : "USER1",
"password" : "USERP"
}
### Get user profile from user
GET http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGZmNTg5ZTJhZjE5MWRlNDVjYzRlYiIsImlhdCI6MTYzMjYzMDgzMiwiZXhwIjoxNjMyNjQxNjMyfQ.LlE0a-8Us2cJsO5LxzrF6oldgCm7pg6k5g-iXFzMVZo
### UPDATE User Profile
PUT http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGZmNTg5ZTJhZjE5MWRlNDVjYzRlYiIsImlhdCI6MTYzMjYzMDgzMiwiZXhwIjoxNjMyNjQxNjMyfQ.LlE0a-8Us2cJsO5LxzrF6oldgCm7pg6k5g-iXFzMVZo
{
"username" : "USERnew" ,
"email" : "usremln@gmail.com",
"password" : "pwdnew
}

### GET ALL
GET http://localhost:5000/api/products/


### GET A SINGLE PRODUCT
# TAKES IN ONLY A VALID OBJECT ID
GET http://localhost:5000/api/products/51bb793aca2ab77a3200000d

